### ISSUE TITLE
Request Right Hand Rule notation as args in StereoNet class

### ISSUE THREAD

**Issue by brunorpinho** [ondrolexa/apsg#1]
Hello Ondrej,

Is it possible to add right hand rule notation to the StereoNet class? I plotted some data and now I can't change the notation displayed in the legend.

**Comment by ondrolexa** [comment]
I think there could be option which will affect notation how data are displayed in both legend and command line. I will try to implement in next release.

**Comment by ondrolexa** [comment]
I just implemented simple per module settings, which can control notation used for planar elements. By default `'dd'` (Dip directip, Dip angle) is used but could be set to `'rhr'` for strike and dip using right hand rule. To use it one need to import settings dictionary and set `'notation'` entry:
```
>>> from apsg import *
>>> from apsg.core import settings
>>> settings['notation']
'dd'
>>> p = Fol(120, 30)
>>> p
S:120/30
>>> settings['notation'] = 'rhr'
>>> p
S:30/30
>>> q=Fol(40,50)
>>> q
S:40/50
>>> settings['notation'] = 'dd'
>>> p
S:120/30
>>> q
S:130/50
```
