### ISSUE TITLE
Use the `master` as the main development branch

### ISSUE THREAD

**Issue by uetoyo** [ondrolexa/apsg#14]
Use the `master` branch as the main development branch. Using a `develop` branch complicates the development process. When you use the `develop` branch all the hot-fixes have to be merged back from  `master` to `develop`. There is also no project activity visible to the repository visitors (potential contributors) unless we merge the `develop` back to `master`, which happens not so often. At least merging to the `master` force us to be more critical when we write or review a new code.

- http://endoflineblog.com/oneflow-a-git-branching-model-and-workflow
- https://www.toptal.com/software/trunk-based-development-git-flow

**Comment by ondrolexa** [comment]
Ok, I think it is reasonable to switch to oneflow model... I just merged current develop branch and discarded develop one.
