### ISSUE TITLE
Remove support for Python 2

### ISSUE THREAD

**Issue by uetoyo** [ondrolexa/apsg#15]
Numpy and Pandas will drop the support for Python 2. 
> Pandas: Starting January 1, 2019, pandas feature releases will support Python 3 only. See Plan for dropping Python 2.7 for more. 
> Numpy: Starting on January 1, 2019, any new feature releases will support only Python3.

If we will remove the Python 2 support wen can use more Python 3 features as typing annotations and dataclasses (new in 3.7).

**Comment by ondrolexa** [comment]
The Python core team plans to stop supporting Python 2 in 2020, so I think we should still keep support for Python 2.

**Comment by uetoyo** [comment]
Please, remove support for Python 2. This package uses no more the few tens of users. If they don't want to upgrade to Python 3 it is only their problem. Python 3 has many nice features as optional type checking via type hints and `mypy`, data classes -- which removes the need for endless `__eq__`, `__hash__`, `__str__` reimplementation. Our package is not for masses why to apply this kind of regression?

**Comment by ondrolexa** [comment]
Included in [PR#24](https://github.com/ondrolexa/apsg/pull/24).
