### ISSUE TITLE
Polar Plotting of Stereonets

### ISSUE THREAD

**Issue by jryoung3** [ondrolexa/apsg#27]
Will there be Polar plotting of stereonets added in the near future?

**Comment by raulindo** [comment]
@jryoung3 for stereonets plotting and related features and calculations,  I would definitely check the `mplstereonet` package at https://github.com/joferkington/mplstereonet since it's built to provide lower-hemisphere equal-area and equal-angle stereonets using mainly matplotlib.

**Comment by ondrolexa** [comment]
The next release of apsg will allow to rotate projection to any position, including polar and both equal-area and equal-angle will be implemented.

**Comment by ondrolexa** [comment]
`StereoNet` keyword argument `overlay_position` allows the user-defined orientation of the grid. For polar plotting, you can use:
```
pos = pair(0, 90, 0, 90)
s = StereoNet(overlay_position=pos)
s.show()
```

**Comment by ManuGraiph** [comment]
For ex., in any StereoNet plot i can't change the grid step:

`s = StereoNet(gridstep=x)`

With x being any number, doesn't work, it always uses 15. 

Actually, i can  put any argument in the constructor and it works without even throwing an error:

`s = StereoNet(xsrttnoaregchgch=3)`

**Comment by ondrolexa** [comment]
Try `overlay_step` and `clip_pole`, e.g.:
```
s = StereoNet(overlay_step=5, clip_pole=10)
```
All keyword arguments will be explained soon in the documentation...
Not recognized kwargs are ignored, that's why not error is thrown...

**Comment by ManuGraiph** [comment]
That one did the trick, thanks.

**Comment by ManuGraiph** [comment]
Btw, i'm using the documentation from the master branch (https://apsg.readthedocs.io/en/master/apsg.plotting.html), i noticed the one in the stable release is slighty different, which one is the most up to date?

**Comment by ondrolexa** [comment]
the master branch of documentation is the most up-to-date... But there are still some remnants of older doc strings. The kwargs for StereoNet are now described... https://apsg.readthedocs.io/en/master/apsg.plotting.html#apsg.plotting.StereoNet

**Comment by ManuGraiph** [comment]
Thanks!

**Comment by raulindo** [comment]
@ondrolexa Question... Is there anyway to create a matplotlib subplots figure like? I've read the source code for the plotting module, but I couldn't find a way to work on that. 
I am trying to create a subplot with 1 row (nrows=1) and 3 columns (ncols=3) and plot line data representing X, Y and Z axis in each stereogram individually.

**Comment by ondrolexa** [comment]
Not in current version, but it could be possible to implement a new method, which will render stereonet to axes passed as argument... I can try to implement it in near future...

**Comment by ondrolexa** [comment]
It is now possible to create figures with multiple subplots. It is just the first implementation, so it could change in the future. Anyway using the master version you can use `render2ax` method of `StereoNet` to plot to any axes. Here is a working example:
```
from apsg import *
import matplotlib.pyplot as plt

f = folset.random_fisher(position=fol(130,60))
l = linset.random_fisher(position=fol(230,30))
s1 = StereoNet()
s1.great_circle(f)

s2 = StereoNet()
s2.contour(l)
s2.line(l, ms=4)

f, (ax1, ax2) = plt.subplots(1, 2, figsize=(10, 5))
s1.render2ax(ax1)
s2.render2ax(ax2)
plt.show()
```
it will produce
![multiple](https://user-images.githubusercontent.com/6851480/201538554-66a7e309-b71e-4fac-9d88-22a7af011dce.png)

**Comment by raulindo** [comment]
@ondrolexa It worked like a charm! Thank you very much!

![teste](https://user-images.githubusercontent.com/47931185/202229266-da72f2ba-ce68-47d9-bd9d-d50bf49edd84.png)
