### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Skuxley** [ondrolexa/apsg#28]
Hi @ondrolexa  

I am currently trying to split the Structure Name into it's separated groups but have no success. Would you be able to suggest a solution?

Depth | Structure Name | Dip | Dip Direction (TN) | Comments
-- | -- | -- | -- | --
562.67 | Magnetite Vein | 77.88 | 290.55 | NaN
614.34 | Magnetite Vein | 52.68 | 67.55 | NaN
743.80 | Magnetite Vein | 59.10 | 18.98 | NaN

```
s=StereoNet()

test_list=[]
for i in vein_names:
    for index in range(len(vein_names)):
        vein_df = []
        test =sg_data.loc[sg_data['Structure Name'] == i]
        test
        sg_vein = Group.from_array(azis = test['Dip Direction (TN)'], 
                    incs = test['Dip'], 
                    typ=Fol , 
                    name=i)
        s.pole(sg_vein,label= i)
s.pole(sg_vein,label= i)
s.contourf(sg_vein, 20, legend=True, sigma=2)
s.show()
```

**Comment by ondrolexa** [comment]
Hi @Skuxley,
as you have your data file in pandas dataframe `sg_data`, I would use the `group_by` method to split dataset and sequentially add individual groups to StereoNet. Something like this:
```
s = StereoNet()

for name, df in sg_data.groupby('Structure Name'):
    g = Group.from_array(df['Dip Direction (TN)'], df['Dip'], typ=Fol, name=name)
    s.pole(g, label=name)

s.show()
```

**Comment by Skuxley** [comment]
Hi @ondrolexa,

From here how would i plot just Magnetite veins? would you filter that out within the loop?

**Comment by ondrolexa** [comment]
So just select rows you need...
```
df = sg_data[sg_data['Structure Name'] == 'Magnetite Vein']
g = Group.from_array(df['Dip Direction (TN)'], df['Dip'], typ=Fol)
s = StereoNet()
s.pole(g, label='Magnetite Veins')
s.show()

```

**Comment by Skuxley** [comment]
Thank you for the help
