### ISSUE TITLE
Question about contour plots

### ISSUE THREAD

**Issue by ManuGraiph** [ondrolexa/apsg#30]
It's possible to, somehow, get the resulting parameters/centroids/density values from a density contour analysis/plot for a set of poles?

I'm guessing it uses Kamb.

**Comment by ondrolexa** [comment]
The contour analysis uses a modified Kamb contouring technique with exponential smoothing (after Vollmer, 1995) and you can show values of contours passing `colorbar=True` keyword argument. By default, the values are multiples of uniform distribution, but passing `sigmanorm=False` the values are actual sigma. 
```
l = linset.random_fisher(n=250, kappa=3)
s = StereoNet()
s.contour(l, colorbar=True)
s.show()
```

To localize maximum value within contoured data, you can use `max_at()` method of the grid.
```
s.grid.max_at()
```

**Comment by ondrolexa** [comment]
Ok, that is not possible now. But I can implement something like `grid.interpolate` method to sample `StereoGrid` at any orientation...

**Comment by ManuGraiph** [comment]
What's the data on the contourplot object? If it can be parsed as a raster, maybe with raster operations it can be done easily.

I mostly plot with plotly/opengl, i'm nto too used to mpl.

**Comment by ManuGraiph** [comment]
Ok, so, the grid.grid has the vectors for.. the surface of the sphere?

How is that projected into the stereonet?

**Comment by ondrolexa** [comment]
I just implemented the method `density_lookup` for `StereoGrid`, which returns contour value at a given position... Here is a usage example:
```
v = linset.random_fisher()
s = StereoNet()
s.contour(v)

s.grid.density_lookup(lin(90, 75))
```

**Comment by ondrolexa** [comment]
and to answer the previous question, vectors are used to create a 2D unstructured triangular grid (they are projected to plane according to the kind of stereonet, Schmidt or Wulff) and `tricontour` is used for contouring.

**Comment by ManuGraiph** [comment]
Great! It's updated in pip/conda? Or just here for now?

**Comment by ondrolexa** [comment]
Just here on a master branch... It will be available on pipy/conda-forge with the next release... To upgrade to master version:
```
pip install --upgrade git+https://github.com/ondrolexa/apsg.git
```

**Comment by ManuGraiph** [comment]
Shit, i thought i answered yesterday... All tested and working flawless, thanks a lotñ mate!
