### ISSUE TITLE
Question about poles/planes in a pandas df column

### ISSUE THREAD

**Issue by ManuGraiph** [ondrolexa/apsg#31]
Hi!
When i add a column of points/planes to a pandas dataframe, they are not shown when printing the dataframe in the "compact" format they usually have when you single print them but rather as an array of points (example in the picture below).

Is there any way to "force" pandas to show the lines/planes in that compact 'dipdir/dip' format in the dataframes?

![image](https://user-images.githubusercontent.com/93348782/201543728-84246373-3b73-48e4-ad86-cc959858284c.png)

**Comment by ondrolexa** [comment]
Hi @ManuGraiph, it turns out that pandas do not honor `__str__` or `__repr__` on iterable objects and vector-like objects are iterable at the moment in apsg. But, in fact, it is not really necessary. I will try to modify it and it should be fixed in the upcoming commit.

**Comment by ManuGraiph** [comment]
Thanks!

**Comment by ondrolexa** [comment]
Done on master... let me know if it works...

**Comment by ManuGraiph** [comment]
I'll try tomorrow, i'm off for today, but thanks!!!

**Comment by ManuGraiph** [comment]
Worked like a charm, thanks a lot!

![image](https://user-images.githubusercontent.com/93348782/201988591-8ae136b3-6422-4607-a80b-221592b3ffec.png)
