### ISSUE TITLE
Safety Factor

### ISSUE THREAD

**Issue by ManuGraiph** [ondrolexa/apsg#33]
Hello!

Sorry if this is not the proper section for questions, but i wanted to ask.. it's possible to calculate the safety factor of a wedge failure planes and the corresponding slope using apsg?

Thanks in advance!

**Comment by ondrolexa** [comment]
There are no rock stability algorithms implemented in apsg, but definitely, apsg could be used for such an analysis.

**Comment by ManuGraiph** [comment]
Ahh ok, thanks!
