### ISSUE TITLE
Question about the poles color

### ISSUE THREAD

**Issue by ManuGraiph** [ondrolexa/apsg#35]
Hi!

I'm trying to plot a large number of poles from a list where each one has a different color, all of them in another list, however, i'm getting an error that the list of colors "is not a valid value for color". The code i'm trying is:

`color_list = [list_of_colors]`
`g = [list_of_poles]`

`s.pole(g,color=color_list,ms=7)`

And i get the error `color_list is not a valid value for color`

I can do, alternatively:

`s.pole(g[i],color=color_list[i],ms=7) for i in range(len(g))`

And works perfect, but it takes waaay longer. I'm guessing i'm missing something in the color input format to make it take a list. Any advice?

**Comment by ondrolexa** [comment]
Did you try `scatter` method of StereoNet?

```
color_list = [list_of_colors]
g = [list_of_poles]  # it must be folset, linset or vecset

s.scatter(g, c=color_list)
```

**Comment by ManuGraiph** [comment]
Omg, sorry! It never notified me of this post!

Yes, that indeed solved the problem, thanks a lot!!
